name: consultations_app
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  shared_preferences: ^2.2.2
  internet_connection_checker: ^1.0.0+1
  bloc: ^8.1.3
  flutter_bloc: ^8.1.4
  cached_network_image: ^3.3.1
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  easy_localization: ^3.0.5
  http: ^1.1.2
  dartz: ^0.10.1
  go_router: ^14.1.4
  get_it: ^7.6.7
  logger: ^2.0.2+1

  flutter_screenutil: ^5.9.0
  flutter_easyloading: ^3.0.5
  loading_animation_widget: ^1.2.0+4
  flutter_inset_box_shadow: ^1.0.8
  shimmer: ^3.0.0
  flutter_svg: ^2.0.9
  bottom_navy_bar: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  awesome_snackbar_content: ^0.1.3
  otp_text_field: ^1.1.3
  image_picker: ^1.1.2
  dropdown_button2: ^2.3.9
  multi_select_flutter: ^4.1.3
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.8
  freezed: ^2.5.2
  json_serializable: ^6.7.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"

flutter_native_splash:
  color: "#150050"
  image: assets/images/splash_screen.png
  android_gravity: fill
  fullscreen: true

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/icons/
    - assets/svgs/images/
